"""add login_attempts updated_at

Revision ID: fa25cd274bc8
Revises: 487705ae4530
Create Date: 2026-10-07 05:56:49.070838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa25cd274bc8'
down_revision: Union[str, None] = '487705ae4530'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('login_attempts', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('login_attempts', 'updated_at')
    # ### end Alembic commands ###
